//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mods
{
    using System;
    using System.Collections.Generic;
    
    public partial class CChuRuBaosunProduct
    {
        public int CRBTPid { get; set; }
        public string BorrowedId { get; set; }
        public string BorrowedName { get; set; }
        public string BorrowedBarcode { get; set; }
        public string Specifications { get; set; }
        public string Batch { get; set; }
        public Nullable<decimal> SinglePrice { get; set; }
        public Nullable<int> StorageCount { get; set; }
        public Nullable<int> DeliveryCount { get; set; }
        public Nullable<int> RefundCount { get; set; }
        public Nullable<int> BreakageCount { get; set; }
        public Nullable<int> StorageNumber { get; set; }
        public Nullable<int> DistinctionState { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Standby1 { get; set; }
        public Nullable<int> Standby2 { get; set; }
        public string Standby3 { get; set; }
        public string Standby4 { get; set; }
    }
}
