//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mods
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int Did { get; set; }
        public string DeliveryId { get; set; }
        public Nullable<int> DeliveryTYpe { get; set; }
        public string ClientNames { get; set; }
        public Nullable<int> TotalCount { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public Nullable<int> DeliveryAuditState { get; set; }
        public string OperatingMode { get; set; }
        public string PreparedBy { get; set; }
        public Nullable<System.DateTime> DispatchTime { get; set; }
        public string ClientId { get; set; }
        public string ClientName { get; set; }
        public string ClientContactWay { get; set; }
        public string ContactMan { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Standby1 { get; set; }
        public Nullable<int> Standby2 { get; set; }
        public string Standby3 { get; set; }
        public string Standby4 { get; set; }
    }
}
