//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mods
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Mid { get; set; }
        public string NodeId { get; set; }
        public string ShowName { get; set; }
        public string NodeSite { get; set; }
        public string ShowOrder { get; set; }
        public string ParentNodelId { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Standby1 { get; set; }
        public Nullable<int> Standby2 { get; set; }
        public string Standby3 { get; set; }
        public string Standby4 { get; set; }
    }
}
