//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mods
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSort
    {
        public int PSid { get; set; }
        public string ProductSortId { get; set; }
        public string ProductSortName { get; set; }
        public string CreationMen { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public string Remark { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Standby1 { get; set; }
        public Nullable<int> Standby2 { get; set; }
        public string Standby3 { get; set; }
        public string Standby4 { get; set; }
    }
}
