//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mods
{
    using System;
    using System.Collections.Generic;
    
    public partial class StStorage
    {
        public int Stoid { get; set; }
        public string StoOrderId { get; set; }
        public Nullable<int> StoType { get; set; }
        public string SuppliersType { get; set; }
        public Nullable<int> GoodsTotal { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public Nullable<int> StStorageState { get; set; }
        public string MakingSingle { get; set; }
        public string SuppliersId { get; set; }
        public string SuppliersName { get; set; }
        public string SuppliersPeople { get; set; }
        public string SuppliersContact { get; set; }
        public Nullable<System.DateTime> OrdersTime { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Standby1 { get; set; }
        public Nullable<int> Standby2 { get; set; }
        public string Standby3 { get; set; }
        public string Standby4 { get; set; }
    }
}
