//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mods
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierTypes
    {
        public int STid { get; set; }
        public string SupplierId { get; set; }
        public string SupplierTypeName { get; set; }
        public Nullable<int> State { get; set; }
    }
}
